name: Deploy backend to Cloud Run

on:
  push:
    branches: [ main, master ]
    paths:
      - 'back/**'
      - '.github/workflows/deploy-backend.yml'

env:
  PROJECT_ID: steam-treat-466702-g9
  REGION: asia-northeast3
  SERVICE_NAME: bigpro-backend
  ARTIFACT_REPO: backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Ensure Artifact Registry repo exists
        run: |
          if ! gcloud artifacts repositories describe ${{ env.ARTIFACT_REPO }} --location=${{ env.REGION }} >/dev/null 2>&1; then
            gcloud artifacts repositories create ${{ env.ARTIFACT_REPO }} \
              --repository-format=docker --location=${{ env.REGION }}
          fi

      - name: Build and push image
        working-directory: ./back
        env:
          IMAGE_URI: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        run: |
          docker build -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 4000 \
            --memory 512Mi \
            --set-env-vars "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}"

